name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt install gcc make git unzip wget xz-utils libsdl2-dev libsdl2-mixer-dev libfreeimage-dev libfreetype6-dev libcurl4-openssl-dev rapidjson-dev libasound2-dev libgl1-mesa-dev build-essential libboost-all-dev cmake fonts-droid-fallback libvlc-dev libvlccore-dev vlc-bin texinfo premake4 golang libssl-dev curl patchelf xmlstarlet patchutils gawk gperf xfonts-utils default-jre python-is-python3 xsltproc libjson-perl lzop libncurses5-dev device-tree-compiler u-boot-tools rsync p7zip libparse-yapp-perl zip binutils-aarch64-linux-gnu dos2unix p7zip-full libvpx-dev bsdmainutils bc meson p7zip-full qemu-user-binfmt zstd parted imagemagick libxml-parser-perl
      - name: Build
        run: make RG351MP
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: output-image
          path: JELOS-RG351MP.aarch64-*.img.gz
